### ISSUE TITLE
To-do next

### ISSUE THREAD

**Issue by brunnomenxa** [brunnomenxa/super-bomberman-4#3]
Fix:
- [ ] Separate items from this list into appropriate new issues.
- [ ] Bomberman animation;
- [ ] Node movable;
- [ ] Colision with blocks.

Add:
- [ ] Death by colision;
- [ ] Player controlls;
- [ ] IA for the Triceratops;
- [ ] Collectibles.
